language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: __token__
  password: $TEST_PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master